In [4]:
import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np

from pathlib import Path

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.width", 150)

In [7]:
df = pd.read_csv("Dataset/MalMem2022.csv")
print("Dataset Loaded Successfully")

Dataset Loaded Successfully

In [9]:
print(df.shape)

(58596, 58)

In [10]:
df.head()

,pslist.nproc,pslist.nppid,pslist.avg_threads,pslist.nprocs64bit,pslist.avg_handlers,dlllist.ndlls,dlllist.avg_dlls_per_proc,handles.nhandles,handles.avg_handles_per_proc,handles.nport,handles.nfile,handles.nevent,handles.ndesktop,handles.nkey,handles.nthread,handles.ndirectory,handles.nsemaphore,handles.ntimer,handles.nsection,handles.nmutant,ldrmodules.not_in_load,ldrmodules.not_in_init,ldrmodules.not_in_mem,ldrmodules.not_in_load_avg,ldrmodules.not_in_init_avg,ldrmodules.not_in_mem_avg,malfind.ninjections,malfind.commitCharge,malfind.protection,malfind.uniqueInjections,psxview.not_in_pslist,psxview.not_in_eprocess_pool,psxview.not_in_ethread_pool,psxview.not_in_pspcid_list,psxview.not_in_csrss_handles,psxview.not_in_session,psxview.not_in_deskthrd,psxview.not_in_pslist_false_avg,psxview.not_in_eprocess_pool_false_avg,psxview.not_in_ethread_pool_false_avg,psxview.not_in_pspcid_list_false_avg,psxview.not_in_csrss_handles_false_avg,psxview.not_in_session_false_avg,psxview.not_in_deskthrd_false_avg,modules.nmodules,svcscan.nservices,svcscan.kernel_drivers,svcscan.fs_drivers,svcscan.process_services,svcscan.shared_process_services,svcscan.interactive_process_services,svcscan.nactive,callbacks.ncallbacks,callbacks.nanonymous,callbacks.ngeneric,Class,Category,Filename
0,45,17,10.555556,0,202.844444,1694,38.500000,9129,212.302326,0,670,3161,46,716,887,104,671,125,184,257,53,95,53,0.030372,0.054441,0.030372,5,21,30,1.250000,2,0,3,2,7,4,9,0.042553,0.0,0.063830,0.042553,0.148936,0.085106,0.191489,138,389,221,26,24,116,0,121,87,0,8,Benign,Benign,Benign
1,47,19,11.531915,0,242.234043,2074,44.127660,11385,242.234043,0,840,3761,51,1011,1030,117,766,148,337,394,77,123,77,0.036167,0.057774,0.036167,12,77,72,1.714286,0,0,0,0,4,2,6,0.000000,0.0,0.000000,0.000000,0.085106,0.042553,0.127660,138,392,222,26,24,118,0,122,87,0,8,Benign,Benign,Benign
2,40,14,14.725000,0,288.225000,1932,48.300000,11529,288.225000,0,1050,3996,45,784,1241,100,645,138,369,338,51,89,51,0.026114,0.045571,0.026114,5,6,30,1.250000,0,0,0,0,4,2,5,0.000000,0.0,0.000000,0.000000,0.100000,0.050000,0.125000,137,395,222,26,27,118,0,120,88,0,8,Benign,Benign,Benign
3,32,13,13.500000,0,264.281250,1445,45.156250,8457,264.281250,0,630,2961,36,654,792,83,567,127,186,242,31,62,31,0.021483,0.042966,0.021483,2,2,12,1.000000,0,0,0,0,4,2,6,0.000000,0.0,0.000000,0.000000,0.125000,0.062500,0.187500,138,395,222,26,27,118,0,120,88,0,8,Benign,Benign,Benign
4,42,16,11.452381,0,281.333333,2067,49.214286,11816,281.333333,0,908,3834,45,1252,942,103,825,135,375,429,102,143,102,0.047820,0.067042,0.047820,12,77,72,2.000000,4,0,4,4,8,6,10,0.086957,0.0,0.086957,0.086957,0.173913,0.130435,0.217391,138,392,222,26,24,118,0,124,87,0,8,Benign,Benign,Benign

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 58596 entries, 0 to 58595
Data columns (total 58 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   pslist.nproc                            58596 non-null  int64
 1   pslist.nppid                            58596 non-null  int64
 2   pslist.avg_threads                      58596 non-null  float64
 3   pslist.nprocs64bit                      58596 non-null  int64
 4   pslist.avg_handlers                     58596 non-null  float64
 5   dlllist.ndlls                           58596 non-null  int64
 6   dlllist.avg_dlls_per_proc               58596 non-null  float64
 7   handles.nhandles                        58596 non-null  int64
 8   handles.avg_handles_per_proc            58596 non-null  float64
 9   handles.nport                           58596 non-null  int64
 10  handles.nfile                           58596 non-null  int64
 11  handles.nevent                          58596 non-null  int64
 12  handles.ndesktop                        58596 non-null  int64
 13  handles.nkey                            58596 non-null  int64
 14  handles.nthread                         58596 non-null  int64
 15  handles.ndirectory                      58596 non-null  int64
 16  handles.nsemaphore                      58596 non-null  int64
 17  handles.ntimer                          58596 non-null  int64
 18  handles.nsection                        58596 non-null  int64
 19  handles.nmutant                         58596 non-null  int64
 20  ldrmodules.not_in_load                  58596 non-null  int64
 21  ldrmodules.not_in_init                  58596 non-null  int64
 22  ldrmodules.not_in_mem                   58596 non-null  int64
 23  ldrmodules.not_in_load_avg              58596 non-null  float64
 24  ldrmodules.not_in_init_avg              58596 non-null  float64
 25  ldrmodules.not_in_mem_avg               58596 non-null  float64
 26  malfind.ninjections                     58596 non-null  int64
 27  malfind.commitCharge                    58596 non-null  int64
 28  malfind.protection                      58596 non-null  int64
 29  malfind.uniqueInjections                58596 non-null  float64
 30  psxview.not_in_pslist                   58596 non-null  int64
 31  psxview.not_in_eprocess_pool            58596 non-null  int64
 32  psxview.not_in_ethread_pool             58596 non-null  int64
 33  psxview.not_in_pspcid_list              58596 non-null  int64
 34  psxview.not_in_csrss_handles            58596 non-null  int64
 35  psxview.not_in_session                  58596 non-null  int64
 36  psxview.not_in_deskthrd                 58596 non-null  int64
 37  psxview.not_in_pslist_false_avg         58596 non-null  float64
 38  psxview.not_in_eprocess_pool_false_avg  58596 non-null  float64
 39  psxview.not_in_ethread_pool_false_avg   58596 non-null  float64
 40  psxview.not_in_pspcid_list_false_avg    58596 non-null  float64
 41  psxview.not_in_csrss_handles_false_avg  58596 non-null  float64
 42  psxview.not_in_session_false_avg        58596 non-null  float64
 43  psxview.not_in_deskthrd_false_avg       58596 non-null  float64
 44  modules.nmodules                        58596 non-null  int64
 45  svcscan.nservices                       58596 non-null  int64
 46  svcscan.kernel_drivers                  58596 non-null  int64
 47  svcscan.fs_drivers                      58596 non-null  int64
 48  svcscan.process_services                58596 non-null  int64
 49  svcscan.shared_process_services         58596 non-null  int64
 50  svcscan.interactive_process_services    58596 non-null  int64
 51  svcscan.nactive                         58596 non-null  int64
 52  callbacks.ncallbacks                    58596 non-null  int64
 53  callbacks.nanonymous                    58596 non-null  int64
 54  callbacks.ngeneric                      58596 non-null  int64
 55  Class                                   58596 non-null  str
 56  Category                                58596 non-null  str
 57  Filename                                58596 non-null  str
dtypes: float64(15), int64(40), str(3)
memory usage: 29.2 MB

In [12]:
df.describe().T

                                          count          mean          std          min          25%          50%           75%           max
pslist.nproc                            58596.0     41.394771     5.777249    21.000000    40.000000    41.000000     43.000000  2.400000e+02
pslist.nppid                            58596.0     14.713837     2.656748     8.000000    12.000000    15.000000     16.000000  7.200000e+01
pslist.avg_threads                      58596.0     11.341655     1.588231     1.650000     9.972973    11.000000     12.861955  1.681818e+01
pslist.nprocs64bit                      58596.0      0.000000     0.000000     0.000000     0.000000     0.000000      0.000000  0.000000e+00
pslist.avg_handlers                     58596.0    247.509819   111.857790    34.962500   208.725000   243.963710    289.974322  2.484595e+04
dlllist.ndlls                           58596.0   1810.805447   329.782639   670.000000  1556.000000  1735.000000   2087.000000  3.443000e+03
dlllist.avg_dlls_per_proc               58596.0     43.707806     5.742023     7.333333    38.833333    42.781524     49.605280  5.317073e+01
handles.nhandles                        58596.0  10258.584221  4866.864130  3514.000000  8393.000000  9287.500000  12193.000000  1.047310e+06
handles.avg_handles_per_proc            58596.0    249.560958   145.999866    71.139241   209.648228   247.208951    291.355050  3.378419e+04
handles.nport                           58596.0      0.000000     0.000000     0.000000     0.000000     0.000000      0.000000  0.000000e+00
handles.nfile                           58596.0    899.119513  3432.351200   266.000000   646.000000   839.000000   1080.000000  8.070080e+05
handles.nevent                          58596.0   3572.409960   805.460522   966.000000  2923.000000  3151.000000   4321.000000  7.892000e+03
handles.ndesktop                        58596.0     44.529166     5.161254    22.000000    43.000000    45.000000     46.000000  1.590000e+02
handles.nkey                            58596.0    774.280668   150.407075   284.000000   675.000000   753.000000    859.000000  2.668000e+03
handles.nthread                         58596.0    928.510086   237.817566   388.000000   708.000000   848.000000   1169.000000  5.637000e+03
handles.ndirectory                      58596.0    102.398338     9.782695    57.000000    99.000000   103.000000    107.000000  4.980000e+02
handles.nsemaphore                      58596.0    683.339324    94.531078   296.000000   614.000000   684.000000    750.000000  4.268000e+03
handles.ntimer                          58596.0    130.327855    14.965266    69.000000   120.000000   131.000000    142.000000  3.820000e+02
handles.nsection                        58596.0    290.127466   144.278832    50.000000   177.000000   224.000000    415.000000  1.468700e+04
handles.nmutant                         58596.0    312.588829    73.173189   118.000000   258.000000   289.000000    366.000000  5.830000e+02
ldrmodules.not_in_load                  58596.0     60.830347    18.761422     6.000000    46.000000    57.000000     74.000000  2.400000e+02
ldrmodules.not_in_init                  58596.0     99.946413    21.438482    16.000000    85.000000    97.000000    115.000000  2.640000e+02
ldrmodules.not_in_mem                   58596.0     60.832599    18.759947     6.000000    46.000000    57.000000     74.000000  2.400000e+02
ldrmodules.not_in_load_avg              58596.0      0.033170     0.009263     0.016176     0.028846     0.031361      0.036430  5.311203e-01
ldrmodules.not_in_init_avg              58596.0      0.055223     0.010112     0.040526     0.052397     0.054036      0.056010  5.850622e-01
ldrmodules.not_in_mem_avg               58596.0      0.033171     0.009266     0.016176     0.028846     0.031361      0.036430  5.311203e-01
malfind.ninjections                     58596.0      7.010274    15.390647     1.000000     3.000000     4.000000      5.000000  6.270000e+02
malfind.commitCharge                    58596.0    969.199229  6041.620916     1.000000     3.000000     4.000000      6.000000  2.208500e+05
malfind.protection                      58596.0     42.282408    92.337061     6.000000    18.000000    24.000000     30.000000  3.762000e+03
malfind.uniqueInjections                58596.0      1.733699     2.741343     1.000000     1.000000     1.250000      1.333333  9.066667e+01
psxview.not_in_pslist                   58596.0      1.875845     2.995955     0.000000     0.000000     1.000000      3.000000  4.300000e+01
psxview.not_in_eprocess_pool            58596.0      0.002082     0.045582     0.000000     0.000000     0.000000      0.000000  1.000000e+00
psxview.not_in_ethread_pool             58596.0      2.273500     4.621418     0.000000     0.000000     1.000000      3.000000  2.010000e+02
psxview.not_in_pspcid_list              58596.0      1.879463     3.017659     0.000000     0.000000     1.000000      3.000000  4.300000e+01
psxview.not_in_csrss_handles            58596.0      6.276572     4.622047     4.000000     4.000000     5.000000      7.000000  2.050000e+02
psxview.not_in_session                  58596.0      3.875589     2.995970     2.000000     2.000000     3.000000      5.000000  4.500000e+01
psxview.not_in_deskthrd                 58596.0      8.256605     4.736886     4.000000     6.000000     7.000000      9.000000  2.070000e+02
psxview.not_in_pslist_false_avg         58596.0      0.040991     0.057563     0.000000     0.000000     0.021739      0.068182  5.512821e-01
psxview.not_in_eprocess_pool_false_avg  58596.0      0.000080     0.001269     0.000000     0.000000     0.000000      0.000000  4.347826e-02
psxview.not_in_ethread_pool_false_avg   58596.0      0.047745     0.066907     0.000000     0.000000     0.023256      0.069767  8.375000e-01
psxview.not_in_pspcid_list_false_avg    58596.0      0.041078     0.058216     0.000000     0.000000     0.021739      0.068182  1.000000e+00
psxview.not_in_csrss_handles_false_avg  58596.0      0.141784     0.061438     0.025806     0.100000     0.119048      0.166180  8.541667e-01
psxview.not_in_session_false_avg        58596.0      0.087964     0.055040     0.008333     0.048780     0.066667      0.113636  5.769231e-01
psxview.not_in_deskthrd_false_avg       58596.0      0.187701     0.061534     0.043750     0.146341     0.166465      0.211691  8.625000e-01
modules.nmodules                        58596.0    137.961465     0.198251   126.000000   138.000000   138.000000    138.000000  1.380000e+02
svcscan.nservices                       58596.0    391.347549     4.529704    94.000000   389.000000   389.000000    395.000000  3.950000e+02
svcscan.kernel_drivers                  58596.0    221.406581     1.991087    55.000000   221.000000   221.000000    222.000000  2.220000e+02
svcscan.fs_drivers                      58596.0     25.996245     0.170790     6.000000    26.000000    26.000000     26.000000  2.600000e+01
svcscan.process_services                58596.0     25.063417     1.529628     7.000000    24.000000    24.000000     27.000000  2.700000e+01
svcscan.shared_process_services         58596.0    116.879514     1.550401    26.000000   116.000000   116.000000    118.000000  1.180000e+02
svcscan.interactive_process_services    58596.0      0.000000     0.000000     0.000000     0.000000     0.000000      0.000000  0.000000e+00
svcscan.nactive                         58596.0    121.995546     2.822858    30.000000   121.000000   122.000000    123.000000  1.290000e+02
callbacks.ncallbacks                    58596.0     86.905659     3.134117    50.000000    87.000000    87.000000     88.000000  8.900000e+01
callbacks.nanonymous                    58596.0      0.000853     0.029199     0.000000     0.000000     0.000000      0.000000  1.000000e+00
callbacks.ngeneric                      58596.0      7.999881     0.010929     7.000000     8.000000     8.000000      8.000000  8.000000e+00

In [13]:
missing = df.isnull().sum()
missing = missing[missing > 0]
missing.sort_values(ascending=False)

Series([], dtype: int64)

In [18]:
duplicates = df.duplicated().sum()
print("Duplicate Rows :", duplicates)

Duplicate Rows : 534

In [19]:
print("Shape Before:", df.shape)
df = df.drop_duplicates().reset_index(drop=True)
print("Shape After :", df.shape)

Shape Before: (58596, 58)
Shape After : (58062, 58)

In [20]:
df["Class"].value_counts()

Class
Benign     29231
Malware    28831
Name: count, dtype: int64

In [21]:
df["Category"].value_counts()

Category
Benign                  29231
Spyware-Transponder      2410
Ransomware-Shade         2128
Ransomware-Ako           2000
Spyware-180solutions     2000
Spyware-CWS              2000
Trojan-Refroso           2000
Trojan-Scar              2000
Spyware-Gator            1995
Ransomware-Conti         1988
Trojan-Emotet            1967
Trojan-Zeus              1950
Ransomware-Maze          1754
Ransomware-Pysa          1659
Trojan-Reconyc           1570
Spyware-TIBS             1410
Name: count, dtype: int64

In [17]:
categorical_columns = df.select_dtypes(include="object").columns
numerical_columns = df.select_dtypes(exclude="object").columns
print("Categorical Columns")
print(categorical_columns)
print()
print("Numerical Columns :", len(numerical_columns))

Categorical Columns
Index(['Class', 'Category', 'Filename'], dtype='str')

Numerical Columns : 55

In [23]:
from pathlib import Path
OUTPUT = Path("../data/processed")
OUTPUT.mkdir(parents=True, exist_ok=True)
df.to_csv(
    OUTPUT/"raw_dataset.csv",
    index=False
)
print("Dataset Saved")

Dataset Saved